import type { Application, ApplicationPeriod, Donation } from "./types";

export const INITIAL_PERIODS: ApplicationPeriod[] = [
  {
    id: "ap-2027-summer",
    title: "Summer 2027 Grant Cycle",
    description:
      "Micro grants supporting early-stage social impact and technology projects across Haiti and the diaspora.",
    startDate: "2026-07-21T00:00:00.000Z",
    endDate: "2026-08-30T23:59:59.999Z",
    maximumGrantAmount: 1000,
    status: "Open",
  },
  {
    id: "ap-2026-spring",
    title: "Spring 2026 Grant Cycle",
    description: "First micro grant cycle focused on agriculture, education, and community health initiatives.",
    startDate: "2026-02-01T00:00:00.000Z",
    endDate: "2026-03-15T23:59:59.999Z",
    maximumGrantAmount: 800,
    status: "Closed",
  },
  {
    id: "ap-2027-winter",
    title: "Winter 2027 Grant Cycle",
    description: "Upcoming cycle prioritizing women-led ventures and clean energy pilots.",
    startDate: "2026-12-01T00:00:00.000Z",
    endDate: "2027-01-15T23:59:59.999Z",
    maximumGrantAmount: 1000,
    status: "Upcoming",
  },
];

const CURRENT = "ap-2027-summer";

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: "app-001",
    trackingId: "IFA-7A5F1953",
    periodId: CURRENT,
    personal: {
      name: "Asadur Rahaman Yead",
      dob: "2000-12-30T00:00:00.000Z",
      nationality: "Bangladeshi",
      location: "Dhaka, Bangladesh",
      image: "https://i.pravatar.cc/400?img=13",
      occupation: "Software Engineer",
      financialBackground:
        "Self-employed software engineer with limited funding available for research and product development.",
    },
    contact: { email: "yead19@gmail.com", phone: "+8801712345678" },
    identification: { nationalId: "1998123456789", passport: "A12345678" },
    grant: {
      projectName: "Smart Farming Initiative",
      projectDescription:
        "Developing a smart farming solution using IoT sensors and AI analytics for small-scale farmers.",
      requestedAmount: 500,
      fundUsage:
        "The grant will be used to purchase sensors, microcontrollers, and cloud hosting for the pilot implementation.",
      expectedImpact:
        "The project aims to improve crop yield, reduce water consumption, and increase farmers' income.",
    },
    documents: [
      {
        id: "doc-001a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200",
        fileName: "national-id.webp",
        mimeType: "image/webp",
        size: 284_120,
      },
      {
        id: "doc-001b",
        type: "proof_of_address",
        url: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200",
        fileName: "proof-of-address.jpg",
        mimeType: "image/jpeg",
        size: 512_340,
      },
      {
        id: "doc-001c",
        type: "business_plan",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        fileName: "business-plan.pdf",
        mimeType: "application/pdf",
        size: 1_284_000,
      },
    ],
    status: "winner",
    fundedAmount: 800,
    award: {
      awardAmount: 800,
      transferDate: "2026-09-05T00:00:00.000Z",
      adminNotes: "Funds transferred via bank wire. Winner confirmed receipt.",
    },
    successStory: "This person is amazing, and so is the project idea. Congratulations!",
    rejectionReason: null,
    createdAt: "2026-07-21T06:57:46.893Z",
    updatedAt: "2026-08-13T08:13:46.453Z",
    reviewedAt: "2026-07-24T08:13:46.430Z",
  },
  {
    id: "app-002",
    trackingId: "IFA-3C81A0F2",
    periodId: CURRENT,
    personal: {
      name: "Marie-Claire Baptiste",
      dob: "1995-06-14T00:00:00.000Z",
      nationality: "Haitian",
      location: "Port-au-Prince, Haiti",
      image: "https://i.pravatar.cc/400?img=45",
      occupation: "Community Health Worker",
      financialBackground: "Works part-time at a local clinic; relies on family support for additional income.",
    },
    contact: { email: "mclaire.baptiste@example.com", phone: "+509 3712 4455" },
    identification: { nationalId: "0092134567", passport: "HT2231908" },
    grant: {
      projectName: "Mobile Maternal Care Unit",
      projectDescription:
        "A mobile clinic bringing prenatal check-ups and health education to rural mothers with limited access to care.",
      requestedAmount: 950,
      fundUsage: "Medical supplies, transport fuel, and printed educational materials for six rural communes.",
      expectedImpact: "Reduce preventable complications and improve prenatal visit rates for 300+ mothers.",
    },
    documents: [
      {
        id: "doc-002a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=1200",
        fileName: "id-card.jpg",
        mimeType: "image/jpeg",
        size: 331_500,
      },
      {
        id: "doc-002b",
        type: "business_plan",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        fileName: "maternal-care-plan.pdf",
        mimeType: "application/pdf",
        size: 980_400,
      },
    ],
    status: "finalist",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: null,
    createdAt: "2026-07-22T10:12:00.000Z",
    updatedAt: "2026-08-01T09:00:00.000Z",
    reviewedAt: "2026-07-26T09:00:00.000Z",
  },
  {
    id: "app-003",
    trackingId: "IFA-9D22B7C4",
    periodId: CURRENT,
    personal: {
      name: "Jean Wesley Pierre",
      dob: "1992-03-02T00:00:00.000Z",
      nationality: "Haitian",
      location: "Cap-Haïtien, Haiti",
      image: "https://i.pravatar.cc/400?img=51",
      occupation: "Agronomist",
      financialBackground: "Runs a small cooperative; income fluctuates seasonally with harvest cycles.",
    },
    contact: { email: "jw.pierre@example.com", phone: "+509 3899 7712" },
    identification: { nationalId: "0087453221", passport: "HT1902334" },
    grant: {
      projectName: "Solar Crop Drying Co-op",
      projectDescription: "Shared solar dryers to reduce post-harvest losses for smallholder farmers.",
      requestedAmount: 700,
      fundUsage: "Solar dryer materials, installation, and cooperative training workshops.",
      expectedImpact: "Cut post-harvest losses by up to 40% for 25 farming families.",
    },
    documents: [
      {
        id: "doc-003a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=1200",
        fileName: "govt-id.jpg",
        mimeType: "image/jpeg",
        size: 298_770,
      },
    ],
    status: "approved",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: null,
    createdAt: "2026-07-23T14:45:00.000Z",
    updatedAt: "2026-07-28T11:20:00.000Z",
    reviewedAt: "2026-07-28T11:20:00.000Z",
  },
  {
    id: "app-004",
    trackingId: "IFA-2E44F1A9",
    periodId: CURRENT,
    personal: {
      name: "Naomi Etienne",
      dob: "1998-09-19T00:00:00.000Z",
      nationality: "Haitian",
      location: "Les Cayes, Haiti",
      image: "https://i.pravatar.cc/400?img=47",
      occupation: "Primary School Teacher",
      financialBackground: "Salaried teacher supporting three siblings; minimal discretionary income.",
    },
    contact: { email: "naomi.etienne@example.com", phone: "+509 3455 8890" },
    identification: { nationalId: "0076123400", passport: "HT2010556" },
    grant: {
      projectName: "Reading Corner Libraries",
      projectDescription: "Pop-up libraries and literacy kits for under-resourced primary schools.",
      requestedAmount: 450,
      fundUsage: "Books, shelving, and reading-club facilitator stipends for four schools.",
      expectedImpact: "Boost reading fluency for 600 students across four schools.",
    },
    documents: [
      {
        id: "doc-004a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?w=1200",
        fileName: "teacher-id.jpg",
        mimeType: "image/jpeg",
        size: 210_990,
      },
    ],
    status: "underReview",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: null,
    createdAt: "2026-07-25T08:30:00.000Z",
    updatedAt: "2026-07-27T16:00:00.000Z",
    reviewedAt: null,
  },
  {
    id: "app-005",
    trackingId: "IFA-6B10C3D8",
    periodId: CURRENT,
    personal: {
      name: "Frantz Deshommes",
      dob: "1990-11-25T00:00:00.000Z",
      nationality: "Haitian",
      location: "Gonaïves, Haiti",
      image: "https://i.pravatar.cc/400?img=59",
      occupation: "Fisherman",
      financialBackground: "Daily-wage fisherman with no access to formal credit.",
    },
    contact: { email: "frantz.d@example.com", phone: "+509 3122 6678" },
    identification: { nationalId: "0061239987", passport: "" },
    grant: {
      projectName: "Cold Storage for Fishers",
      projectDescription: "A shared solar-powered cold box so fishers can preserve the daily catch.",
      requestedAmount: 600,
      fundUsage: "Solar cold storage unit and battery bank for a fishing cooperative.",
      expectedImpact: "Reduce spoilage and increase income for 15 fishing families.",
    },
    documents: [],
    status: "submitted",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: null,
    createdAt: "2026-07-26T12:05:00.000Z",
    updatedAt: "2026-07-26T12:05:00.000Z",
    reviewedAt: null,
  },
  {
    id: "app-006",
    trackingId: "IFA-4F77E0B1",
    periodId: CURRENT,
    personal: {
      name: "Widline Joseph",
      dob: "1997-01-08T00:00:00.000Z",
      nationality: "Haitian",
      location: "Jacmel, Haiti",
      image: "https://i.pravatar.cc/400?img=44",
      occupation: "Artisan",
      financialBackground: "Sells handmade crafts at local markets with irregular income.",
    },
    contact: { email: "widline.joseph@example.com", phone: "+509 3600 1298" },
    identification: { nationalId: "0053221190", passport: "HT2245901" },
    grant: {
      projectName: "Artisan Collective Storefront",
      projectDescription: "An online storefront to sell local artisan crafts to the diaspora market.",
      requestedAmount: 400,
      fundUsage: "Photography equipment, packaging, and first-year hosting costs.",
      expectedImpact: "Open export income for a 12-member women's artisan collective.",
    },
    documents: [
      {
        id: "doc-006a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1200",
        fileName: "artisan-id.jpg",
        mimeType: "image/jpeg",
        size: 187_220,
      },
    ],
    status: "submitted",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: null,
    createdAt: "2026-07-27T09:40:00.000Z",
    updatedAt: "2026-07-27T09:40:00.000Z",
    reviewedAt: null,
  },
  {
    id: "app-007",
    trackingId: "IFA-8A93D5E2",
    periodId: CURRENT,
    personal: {
      name: "Ricardo Alcin",
      dob: "1988-05-30T00:00:00.000Z",
      nationality: "Haitian",
      location: "Pétion-Ville, Haiti",
      image: "https://i.pravatar.cc/400?img=68",
      occupation: "Mechanic",
      financialBackground: "Operates a small garage; savings depleted after equipment repairs.",
    },
    contact: { email: "ricardo.alcin@example.com", phone: "+509 3788 4521" },
    identification: { nationalId: "0044120087", passport: "" },
    grant: {
      projectName: "EV Scooter Repair Hub",
      projectDescription: "A repair and charging hub for electric scooters used by delivery riders.",
      requestedAmount: 1000,
      fundUsage: "Charging station, diagnostic tools, and spare parts inventory.",
      expectedImpact: "Support 40+ delivery riders with affordable maintenance.",
    },
    documents: [
      {
        id: "doc-007a",
        type: "government_id",
        url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200",
        fileName: "id.jpg",
        mimeType: "image/jpeg",
        size: 265_400,
      },
    ],
    status: "rejected",
    fundedAmount: null,
    award: null,
    successStory: null,
    rejectionReason: "Requested amount exceeds what the current pilot budget can responsibly support this cycle.",
    createdAt: "2026-07-24T15:20:00.000Z",
    updatedAt: "2026-07-29T10:15:00.000Z",
    reviewedAt: "2026-07-29T10:15:00.000Z",
  },
  {
    id: "app-008",
    trackingId: "IFA-1B55A9C7",
    periodId: "ap-2026-spring",
    personal: {
      name: "Gladys Toussaint",
      dob: "1994-08-11T00:00:00.000Z",
      nationality: "Haitian",
      location: "Hinche, Haiti",
      image: "https://i.pravatar.cc/400?img=24",
      occupation: "Nurse",
      financialBackground: "Public hospital nurse supporting extended family on a single income.",
    },
    contact: { email: "gladys.toussaint@example.com", phone: "+509 3944 2210" },
    identification: { nationalId: "0031887654", passport: "HT1788221" },
    grant: {
      projectName: "Community First-Aid Training",
      projectDescription: "Weekend first-aid certification for community volunteers in rural clinics.",
      requestedAmount: 300,
      fundUsage: "Training kits, certification materials, and facilitator costs.",
      expectedImpact: "Certify 80 community first responders across the Central Plateau.",
    },
    documents: [
      {
        id: "doc-008a",
        type: "business_plan",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
        fileName: "training-plan.pdf",
        mimeType: "application/pdf",
        size: 640_000,
      },
    ],
    status: "archived",
    fundedAmount: 300,
    award: {
      awardAmount: 300,
      transferDate: "2026-03-20T00:00:00.000Z",
      adminNotes: "Prior cycle winner. Archived after cycle close.",
    },
    successStory: "Gladys trained an entire network of volunteers who now serve their communities.",
    rejectionReason: null,
    createdAt: "2026-02-05T09:00:00.000Z",
    updatedAt: "2026-03-25T12:00:00.000Z",
    reviewedAt: "2026-02-20T10:00:00.000Z",
  },
];

export const INITIAL_DONATIONS: Donation[] = [
  {
    id: "don-001",
    donor: "Emmanuel Georges",
    email: "e.georges@example.com",
    amount: 500,
    transactionId: "TXN-9F2A81C0",
    date: "2026-07-10T09:24:00.000Z",
  },
  {
    id: "don-002",
    donor: "Diaspora Impact Fund",
    email: "give@diasporaimpact.org",
    amount: 400,
    transactionId: "TXN-4B77E120",
    date: "2026-07-14T14:02:00.000Z",
  },
  {
    id: "don-003",
    donor: "Sarah Lemaire",
    email: "sarah.lemaire@example.com",
    amount: 150,
    transactionId: "TXN-2C10D934",
    date: "2026-07-18T18:45:00.000Z",
  },
  {
    id: "don-004",
    donor: "Anonymous",
    email: "hidden@ifundayiti.org",
    amount: 100,
    transactionId: "TXN-7A9B0C55",
    date: "2026-07-19T08:11:00.000Z",
  },
  {
    id: "don-005",
    donor: "Northbridge Rotary Club",
    email: "contact@northbridgerotary.org",
    amount: 750,
    transactionId: "TXN-6E31F208",
    date: "2026-08-02T11:30:00.000Z",
  },
];
